name: GitHub Organization Repository Metrics Report Action
description: 'A GitHub Action to generate a report that contains various metrics for all repositories belonging to a GitHub organization.'

inputs:
  token:
    description: 'A Personal Access token with repo scope'
    required: false
  org:
    description: 'GitHub organization to retrieve data from'
    default: ''
    required: false
  team:
    description: 'GitHub team to retrieve data from'
    default: ''
    required: false
  days:
    description: 'Amount of days in the past to collect data for'
    default: '30'
    required: false
  sort:
    description: 'Select sorting column'
    default: 'openedPullRequests'
    required: false
  sort-order:
    description: 'Selected column sorting direction'
    default: 'desc'
    required: false
  stale:
    description: 'Amount of days for an issue to be marked as stale'
    default: '14'
    required: false
  old:
    description: 'Amount of days for an issue to be marked as old'
    default: '120'
    required: false
  json:
    description: 'Optional report export in JSON format'
    default: 'false'
    required: false
  diff-report:
    description: 'Use identical file name for future reports'
    default: 'false'
    required: false
  fromdate:
    description: 'The date from which to start collecting data'
    required: false
  todate:
    description: 'The date to which to stop collecting data'
    required: false
  committer-name:
    description: 'The name of the committer that will appear in the Git history'
    default: 'github-actions'
    required: false
  committer-email:
    description: 'The committer email that will appear in the Git history'
    default: 'github-actions@github.com'
    required: false
  appid:
    required: false
  privatekey:
    required: false
  installationid:
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'list'
  color: 'blue'
